### ISSUE TITLE
Join crystal-community?

### ISSUE THREAD

**Issue by benoist** [crystal-community/crystal-ann#29]
Hi would you be open to joining the crystal-community with adding the crystal-ann repo there?

**Comment by veelenga** [comment]
@benoist hey, thanks for the suggestion.

This is a good idea. One thing I worry about is an *isolation*. Currently, we have an organization with other [related repos](https://github.com/crystal-announcements), which as for me fits perfectly to isolate the project/forks/team.

Being a part of crystal-community organization means we need to maintain a fork, for example, in another place, right?

Maybe we can just mirror this repository in crystal-community org and periodically synchronize it? In terms of git, this should not be difficult to just push it into two origins. At least we can start with this approach and completely move to crystal-community if we face with other difficulties...  

Or this does not make sense?

@hugoabonizio @benoist  what're your thoughts?

**Comment by benoist** [comment]
Thanks for considering!

> Being a part of crystal-community organization means we need to maintain a fork, for example, in another place, right?

You can become a member of the crystal-community organisation and be in full control of every repo you add to the organisation. Would you require to maintain a fork given that control?

**Comment by veelenga** [comment]
Yes. We maintain this fork [twitter.cr](https://github.com/crystal-announcements/twitter.cr) to make tweets, but I am not interested in developing new features there or support it. I meant that community will not be interested in such kind of project so definitely we would need to maintain it in another place...

**Comment by hugoabonizio** [comment]
In my opinion crystal-community is a nice effort to unite the community in growing the Crystal ecosystem. I think crystal-ann fits well on this purpose as a great tool to announce what's happening but I don't know if makes difference whether this repo is inside the organization or not.

**Comment by veelenga** [comment]
I agree with this. And this is not such a big project to require its own org. 

Okay, let's move it 🎉

**Comment by veelenga** [comment]
@benoist @hugoabonizio let's move [autolink.cr](https://github.com/crystal-announcements/autolink.cr) as well?

**Comment by benoist** [comment]
Yeah thats a nice addition!

**Comment by veelenga** [comment]
@hugoabonizio just need your ok

**Comment by veelenga** [comment]
Hm, interesting, now I don't have access to repo's settings: https://github.com/crystal-community/crystal-ann/settings

**Comment by hugoabonizio** [comment]
OK! :smile: 

But I don't have the permissions on crystal-community org to move the repo yet!

**Comment by veelenga** [comment]
@benoist could you please add @hugoabonizio to @crystal-community/crystal-ann team and grant this team with write access to crystal-ann and autolink.cr repos?
