### ISSUE TITLE
Improve rss feed

### ISSUE THREAD

**Issue by veelenga** [crystal-community/crystal-ann#41]
https://crystal-ann.com/rss

Would be nice to display additional information in rss entry description:

1. announcement tag
2. announcement author
3. submit time in words

**Comment by janczer** [comment]
Hi, I would like work on this issue.

I understand that announcement author I can get from `announcement.user`.
How can I get tag?

And what's mean 'time in words'?

Thank you

**Comment by veelenga** [comment]
Great 👍 

1. `announcement.typename`
2. `announcement.user.login`
3. `time_ago_in_words(announcement.created_at.not_nil!)`

You may find an example in [announcement view](https://github.com/crystal-community/crystal-ann/blob/master/src/views/announcement/_entry.slang).

**Comment by janczer** [comment]
Users login, type and time in words should be formated on some way?
Maybe something like this:

```
<description>User: TestLogin (Project update) - 34 minutes ago &lt;p&gt;desc&lt;/p&gt;</description>
```

**Comment by veelenga** [comment]
@janczer would be really nice to to have those new attributes below the description (just like in the original html view). So maybe something like this:

```
<description>
  desc...
  <hr>
  <small>Project update.</small>
  <small>Announced 34 minutes ago by TestLogin</small>
</description>
```

Also please link `TestLogin` to user's github profile.

Thanks a lot!
