### ISSUE TITLE
"Retweet this announcement" link

### ISSUE THREAD

**Issue by veelenga** [crystal-community/crystal-ann#42]
Add a new link to the footer (at the right) of the announcement. Use [fa-retweet](http://fontawesome.io/icon/retweet/) icon. Use `target="_blank"`, so the link will be opened in a new tab.

Url should be constructed as follows:

```
https://twitter.com/share?text=#{announcement.title}&url=#{SITE.url}#{announcement.short_path}&via=crystallang_ann&related=crystallang_ann
```

For example:

https://twitter.com/share?text=HTTP-Protection:+protect+your+app+against+typical+web+attacks&via=crystallang_ann&related=crystallang-ann&url=https://crystal-ann.com/=Ek87n

**Comment by lex111** [comment]
@veelenga assign to me please, I'll try.

**Comment by veelenga** [comment]
@lex111 sure 👍  Let me know if you will need some help in setting up the environment.

**Comment by vivekagal1998** [comment]
@veelenga Retweeted!!

**Comment by veelenga** [comment]
@vivekagal1998 
Thanks, but the idea is to implement a new external link for our app, not just to click a link in the description 😄

**Comment by lex111** [comment]
@veelenga Correct? 

![image](https://user-images.githubusercontent.com/4408379/31065560-e706f3f8-a74e-11e7-8107-c933cde68934.png)

But there is one problem:
![image](https://user-images.githubusercontent.com/4408379/31065580-22f8d49e-a74f-11e7-9fd0-6905faee471c.png)

It is necessary somehow to cut out all markdown-syntax, leaving only the text..

**Comment by lex111** [comment]
Although wait, why do we use the `description`, not the `title`?

**Comment by veelenga** [comment]
It has to be `title`. Sorry, my fault. 

Please move button to the right, where edit/delete buttons are placed (and remove `Retweet` word).

**Comment by lex111** [comment]
And more a question: the retweet link needs to be defined in the controller? Or in the view just output?

**Comment by veelenga** [comment]
Just in the view.

You may want to join [gitter](https://gitter.im/veelenga/crystal-ann?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) room if you would have other questions.

Or just create a pull request and we will discuss it there...

**Comment by lex111** [comment]
Allright, created PR #45.
