### ISSUE TITLE
Web App Manifest

### ISSUE THREAD

**Issue by veelenga** [crystal-community/crystal-ann#46]
Create `manifest.json` file and a set of icons (at least 3 sizes). Take this [file](https://github.com/veelenga/bin/blob/master/crystal-ann/logo.jpg) as an original icon.

For more information refer to [The Web App Manifest](https://developers.google.com/web/fundamentals/web-app-manifest/?utm_source=devtools).
For live example refer to [web-application-manifest](https://github.com/GoogleChrome/samples/tree/gh-pages/web-application-manifest).

**Comment by vaibhavsingh97** [comment]
Can i take this issue?

**Comment by veelenga** [comment]
Sure 👍

**Comment by vaibhavsingh97** [comment]
@veelenga Need different size of logo if you want different size of launcher icons 😄

**Comment by vaibhavsingh97** [comment]
@veelenga Also, please tell me what theme color i should use. Also, What should I add in name, short name and description

**Comment by veelenga** [comment]
@vaibhavsingh97 sorry, but creation a set of icons is a part of a the task. Are you ok with that?

Name: Crystal Announcements
Short Name: Crystal ANN
Desription: Announce new project, blog post, version update or any other Crystal work
Background Color: `#F1F1F1`
Theme Color: `#FFFFFF`

**Comment by hugoabonizio** [comment]
I think this can be useful: https://resizeappicon.com/

**Comment by veelenga** [comment]
Let's choose:

* 48x48
* 72x72
* 80x80
* 96x96
* 144x144
* 192x192

**Comment by vaibhavsingh97** [comment]
@veelenga Sure! PR is on the way 😄

**Comment by vaibhavsingh97** [comment]
@veelenga what should i use in start url?
