### ISSUE TITLE
All links with target="_blank" should have rel="noopener noreferrer"

### ISSUE THREAD

**Issue by veelenga** [crystal-community/crystal-ann#54]
Search links with target="_blank" across the repository and add `rel="noopener noreferrer"`.

See [Target="_blank" - the most underestimated vulnerability ever](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/) for details

**Comment by PAPERPANKS** [comment]
i will do it

**Comment by veelenga** [comment]
@PAPERPANKS great 👍

**Comment by PAPERPANKS** [comment]
so according to you the code should be -

`<a href="https://abc.xyz" target="_blank" rel="noopener noreferrer">some lorem text</a>`

**Comment by veelenga** [comment]
Yes, correct
