### ISSUE TITLE
Upgrade to amber v0.3.0

### ISSUE THREAD

**Issue by veelenga** [crystal-community/crystal-ann#58]
https://github.com/amberframework/amber/releases/tag/v0.3.0

**Comment by hugoabonizio** [comment]
Amber is using kilt version ```~> 0.3.3``` and Kemal (Sidekiq's dependency) requires ```~> 0.4.0``` :confused:

```
$ shards install
Updating https://github.com/kemalyst/granite-orm.git
(...)
Error resolving kilt (~> 0.4.0, ~> 0.3.3)
```

**Comment by veelenga** [comment]
Hm, maybe we can upgrade kilt on Amber ?

But this dependency error resolving happens really often. Would be nice to exclude kemal somehow, we don't use it. But since this is a transitional dependency, it might be impossible to do at the moment.

**Comment by hugoabonizio** [comment]
I think upgrading kilt on amber would be the best options for now.

I tried to simply replace with version ```0.4.0``` but it seems to break the specs.

**Comment by veelenga** [comment]
I gave it a try.

**Comment by veelenga** [comment]
@hugoabonizio you may try upgrading to amber at `veelenga:feat/upgrade-kilt`. Would you?

**Comment by hugoabonizio** [comment]
@veelenga using your branch worked for me, but the specs are failing.

```yaml
amber:
    github: veelenga/amber
    branch: feat/upgrade-kilt
```

```
$ crystal spec
Error in line 1: while requiring "./spec/helpers/time_ago_helper_spec.cr"

in spec/helpers/time_ago_helper_spec.cr:1: while requiring "../spec_helper"

require "../spec_helper"
^

in spec/spec_helper.cr:5: while requiring "../config/application"

require "../config/application"
^

in config/application.cr:7: instantiating 'Amber::Server:Class#configure()'

Amber::Server.configure do |app|
              ^~~~~~~~~

in config/application.cr:7: instantiating 'Amber::Server:Class#configure()'

Amber::Server.configure do |app|
              ^~~~~~~~~

in config/application.cr:12: undefined method 'env=' for Amber::Settings:Class

  app.env = AMBER_ENV.to_s
      ^~~

Rerun with --error-trace to show a complete error trace.
```

Am I missing something?

**Comment by veelenga** [comment]
@hugoabonizio i think you faced with one of the breaking changes in amber v0.3.0. I will try it locally tomorrow

https://github.com/amberframework/amber/pull/305

**Comment by hugoabonizio** [comment]
You're right!
