### ISSUE TITLE
Failed to install Crystal-Ann: amber db migrate doesn't work

### ISSUE THREAD

**Issue by DRVTiny** [crystal-community/crystal-ann#69]
Using:
Amber 0.6.7, 
Crystal-Ann from the current master/HEAD

 - i cant install Crystal-Ann blogging platform because installation fails on "db migrate" stage:

```
$ amber db migrate                         
no driver was registered for the schema "", did you maybe forget to require the database driver?
```
I presume the problem is "too fresh version" of Amber, which is trying to use some other .yml configuratio file for database connection:

```
$ strace amber db migrate 2>&1 | fgrep .yml | fgrep -v shard
access("/home/akkerman/Apps/Crystal/crystal-ann/config/environments/development.yml", F_OK) = -1 ENOENT (No such file or directory)
```

But i dont know, how to fix this problem (where to get correct development.yml file).
Please, help me to install your robust and featureful blogging platform!

**Comment by veelenga** [comment]
Export database url manually before running the migrations:

```
export DATABASE_URL=postgresql://localhost/crystal_ann
amber db migrate
```

### Description

Unfortunately, crystal-ann has been written before some major features added to Amber. One of such features was a migration. So, crystal-ann does not follow the convention with `environments/development.yml` file and uses a [custom implementation](https://github.com/crystal-community/crystal-ann/blob/master/config/database.yml), which amber-cli now does not understand.

I will upgrade Amber version to the latest one and follow the conventions, so setting up the project will not be a pain.

**Comment by DRVTiny** [comment]
veelenga, thank you very much, it works now! :)
Yeah, Amber is very young framework, so i was expecting something like this. Its awesome that problem with not-worked migration  can be solved in so simple and straightforward way. I was expecting something worse, including deeply digging to the Crystal-Ann or Amber code :)

How to ask some other, not issue-related, questions about Crystal-Ann?

**Comment by veelenga** [comment]
You can use gitter for that: https://gitter.im/veelenga/crystal-ann
