### ISSUE TITLE
Invalid SSL certificate or something

### ISSUE THREAD

**Issue by watzon** [crystal-community/crystal-ann#71]
I can't authenticate with GitHub on Chrome or Firefox. I've discussed this with somone on Gitter and apparently Edge is still working.
![20190520_220632](https://user-images.githubusercontent.com/4535422/58069797-8c698500-7b4b-11e9-9e3e-c1e40cab18f9.jpg)

**Comment by veelenga** [comment]
Fixed

**Comment by carcinocron** [comment]
same problem, but 2 years later

**Comment by veelenga** [comment]
That's because I stopped paying for the Heroku dyno, thus the SSL certificate was disabled. 

Now it is up again.
