### ISSUE TITLE
Expired Certificate

### ISSUE THREAD

**Issue by michelboaventura** [crystal-community/crystal-ann#75]
Hey folks. Not sure if this is the best place to report, but the Let's Encrypt certificate from https://crystal-ann.com has been expired since Mon, 30 May 2022 06:52:20 GMT.

**Comment by denisgolius** [comment]
> Hey folks. Not sure if this is the best place to report, but the Let's Encrypt certificate from https://crystal-ann.com has been expired since Mon, 30 May 2022 06:52:20 GMT.

Hi!
Thanks for ping, issue has been fixed 😉

**Comment by michelboaventura** [comment]
Thanks!
